// Generated by CoffeeScript 1.9.2
(function() {
  var methods;

  methods = {
    isLesserThan: function(other) {
      return this.compareTo(other) < 0;
    },
    isGreaterThan: function(other) {
      return this.compareTo(other) > 0;
    },
    equals: function(other) {
      return this.compareTo(other) === 0;
    },
    isLesserOrEqualThan: function(other) {
      return this.compareTo(other) <= 0;
    },
    isGreaterOrEqualThan: function(other) {
      return this.compareTo(other) >= 0;
    },
    isBetween: function(min, max) {
      return this.isGreaterOrEqualThan(min) && this.isLesserOrEqualThan(max);
    },
    isOutside: function(min, max) {
      return !this.isBetween(min, max);
    }
  };

  module.exports = methods;

}).call(this);
