// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = {
    getWeekNumber: function(day) {
      var yearStart;
      day.setHours(0, 0, 0);
      day.setDate(day.getDate() + 4 - (day.getDay() || 7));
      yearStart = new Date(day.getFullYear(), 0, 1);
      console.log(yearStart.getFullYear());
      return Math.ceil((((day - yearStart) / 86400000) + 1) / 7);
    }
  };

}).call(this);
