// Generated by CoffeeScript 1.9.2
(function() {
  var slice = [].slice;

  module.exports = {
    extend: function() {
      var i, len, method, mixin, mixins, name, obj;
      obj = arguments[0], mixins = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      for (i = 0, len = mixins.length; i < len; i++) {
        mixin = mixins[i];
        for (name in mixin) {
          method = mixin[name];
          obj[name] = method;
        }
      }
      return obj;
    },
    include: function() {
      var klass, mixins;
      klass = arguments[0], mixins = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      this.extend.apply(this, [klass.prototype].concat(slice.call(mixins)));
      return klass;
    }
  };

}).call(this);
